/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.5 at Wed Nov  2 13:36:37 2016. */

#include "sparkplug_b.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t com_cirruslink_sparkplug_protobuf_Payload_fields[7] = {
    PB_FIELD(  1, UINT64  , OPTIONAL, STATIC  , FIRST, com_cirruslink_sparkplug_protobuf_Payload, timestamp, timestamp, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload, metric, timestamp, &com_cirruslink_sparkplug_protobuf_Payload_Metric_fields),
    PB_FIELD(  3, UINT64  , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload, seq, metric, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload, uuid, seq, 0),
    PB_FIELD(  5, BYTES   , OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload, body, uuid, 0),
    PB_FIELD(  6, EXTENSION, OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload, extensions, body, 0),
    PB_LAST_FIELD
};

const pb_field_t com_cirruslink_sparkplug_protobuf_Payload_Template_fields[8] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, FIRST, com_cirruslink_sparkplug_protobuf_Payload_Template, name, name, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_Template, version, name, 0),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_Template, metrics, version, &com_cirruslink_sparkplug_protobuf_Payload_Metric_fields),
    PB_FIELD(  4, MESSAGE , REPEATED, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_Template, properties, metrics, &com_cirruslink_sparkplug_protobuf_Payload_Template_Property_fields),
    PB_FIELD(  5, STRING  , OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_Template, template_ref, properties, 0),
    PB_FIELD(  6, BOOL    , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Template, is_definition, template_ref, 0),
    PB_FIELD(  7, EXTENSION, OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_Template, extensions, is_definition, 0),
    PB_LAST_FIELD
};

const pb_field_t com_cirruslink_sparkplug_protobuf_Payload_Template_Property_fields[10] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, FIRST, com_cirruslink_sparkplug_protobuf_Payload_Template_Property, name, name, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Template_Property, type, name, 0),
    PB_ONEOF_FIELD(value,   3, UINT32  , ONEOF, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Template_Property, int_value, type, 0),
    PB_ONEOF_FIELD(value,   4, UINT64  , ONEOF, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Template_Property, long_value, type, 0),
    PB_ONEOF_FIELD(value,   5, FLOAT   , ONEOF, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Template_Property, float_value, type, 0),
    PB_ONEOF_FIELD(value,   6, DOUBLE  , ONEOF, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Template_Property, double_value, type, 0),
    PB_ONEOF_FIELD(value,   7, BOOL    , ONEOF, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Template_Property, boolean_value, type, 0),
    PB_ONEOF_FIELD(value,   8, STRING  , ONEOF, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Template_Property, string_value, type, 0),
    PB_ONEOF_FIELD(value,   9, MESSAGE , ONEOF, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Template_Property, extension_value, type, &com_cirruslink_sparkplug_protobuf_Payload_Template_Property_PropertyValueExtension_fields),
    PB_LAST_FIELD
};

const pb_field_t com_cirruslink_sparkplug_protobuf_Payload_Template_Property_PropertyValueExtension_fields[2] = {
    PB_FIELD(  1, EXTENSION, OPTIONAL, CALLBACK, FIRST, com_cirruslink_sparkplug_protobuf_Payload_Template_Property_PropertyValueExtension, extensions, extensions, 0),
    PB_LAST_FIELD
};

const pb_field_t com_cirruslink_sparkplug_protobuf_Payload_DataSet_fields[6] = {
    PB_FIELD(  1, UINT64  , OPTIONAL, STATIC  , FIRST, com_cirruslink_sparkplug_protobuf_Payload_DataSet, num_of_columns, num_of_columns, 0),
    PB_FIELD(  2, STRING  , REPEATED, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_DataSet, columns, num_of_columns, 0),
    PB_FIELD(  3, UINT32  , REPEATED, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_DataSet, type, columns, 0),
    PB_FIELD(  4, MESSAGE , REPEATED, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_DataSet, rows, type, &com_cirruslink_sparkplug_protobuf_Payload_DataSet_Row_fields),
    PB_FIELD(  5, EXTENSION, OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_DataSet, extensions, rows, 0),
    PB_LAST_FIELD
};

const pb_field_t com_cirruslink_sparkplug_protobuf_Payload_DataSet_DataSetValue_fields[8] = {
    PB_ONEOF_FIELD(value,   1, UINT32  , ONEOF, STATIC  , FIRST, com_cirruslink_sparkplug_protobuf_Payload_DataSet_DataSetValue, int_value, int_value, 0),
    PB_ONEOF_FIELD(value,   2, UINT64  , ONEOF, STATIC  , FIRST, com_cirruslink_sparkplug_protobuf_Payload_DataSet_DataSetValue, long_value, long_value, 0),
    PB_ONEOF_FIELD(value,   3, FLOAT   , ONEOF, STATIC  , FIRST, com_cirruslink_sparkplug_protobuf_Payload_DataSet_DataSetValue, float_value, float_value, 0),
    PB_ONEOF_FIELD(value,   4, DOUBLE  , ONEOF, STATIC  , FIRST, com_cirruslink_sparkplug_protobuf_Payload_DataSet_DataSetValue, double_value, double_value, 0),
    PB_ONEOF_FIELD(value,   5, BOOL    , ONEOF, STATIC  , FIRST, com_cirruslink_sparkplug_protobuf_Payload_DataSet_DataSetValue, boolean_value, boolean_value, 0),
    PB_ONEOF_FIELD(value,   6, STRING  , ONEOF, STATIC  , FIRST, com_cirruslink_sparkplug_protobuf_Payload_DataSet_DataSetValue, string_value, string_value, 0),
    PB_ONEOF_FIELD(value,   7, MESSAGE , ONEOF, STATIC  , FIRST, com_cirruslink_sparkplug_protobuf_Payload_DataSet_DataSetValue, extension_value, extension_value, &com_cirruslink_sparkplug_protobuf_Payload_DataSet_DataSetValue_DataSetValueExtension_fields),
    PB_LAST_FIELD
};

const pb_field_t com_cirruslink_sparkplug_protobuf_Payload_DataSet_DataSetValue_DataSetValueExtension_fields[2] = {
    PB_FIELD(  1, EXTENSION, OPTIONAL, CALLBACK, FIRST, com_cirruslink_sparkplug_protobuf_Payload_DataSet_DataSetValue_DataSetValueExtension, extensions, extensions, 0),
    PB_LAST_FIELD
};

const pb_field_t com_cirruslink_sparkplug_protobuf_Payload_DataSet_Row_fields[3] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, com_cirruslink_sparkplug_protobuf_Payload_DataSet_Row, elements, elements, &com_cirruslink_sparkplug_protobuf_Payload_DataSet_DataSetValue_fields),
    PB_FIELD(  2, EXTENSION, OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_DataSet_Row, extensions, elements, 0),
    PB_LAST_FIELD
};

const pb_field_t com_cirruslink_sparkplug_protobuf_Payload_PropertyValue_fields[11] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, com_cirruslink_sparkplug_protobuf_Payload_PropertyValue, type, type, 0),
    PB_ONEOF_FIELD(value,   2, UINT32  , ONEOF, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_PropertyValue, int_value, type, 0),
    PB_ONEOF_FIELD(value,   3, UINT64  , ONEOF, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_PropertyValue, long_value, type, 0),
    PB_ONEOF_FIELD(value,   4, FLOAT   , ONEOF, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_PropertyValue, float_value, type, 0),
    PB_ONEOF_FIELD(value,   5, DOUBLE  , ONEOF, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_PropertyValue, double_value, type, 0),
    PB_ONEOF_FIELD(value,   6, BOOL    , ONEOF, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_PropertyValue, boolean_value, type, 0),
    PB_ONEOF_FIELD(value,   7, STRING  , ONEOF, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_PropertyValue, string_value, type, 0),
    PB_ONEOF_FIELD(value,   8, MESSAGE , ONEOF, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_PropertyValue, propertyset_value, type, &com_cirruslink_sparkplug_protobuf_Payload_PropertySet_fields),
    PB_ONEOF_FIELD(value,   9, MESSAGE , ONEOF, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_PropertyValue, propertysets_value, type, &com_cirruslink_sparkplug_protobuf_Payload_PropertySetList_fields),
    PB_ONEOF_FIELD(value,  10, MESSAGE , ONEOF, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_PropertyValue, extension_value, type, &com_cirruslink_sparkplug_protobuf_Payload_PropertyValue_PropertyValueExtension_fields),
    PB_LAST_FIELD
};

const pb_field_t com_cirruslink_sparkplug_protobuf_Payload_PropertyValue_PropertyValueExtension_fields[2] = {
    PB_FIELD(  1, EXTENSION, OPTIONAL, CALLBACK, FIRST, com_cirruslink_sparkplug_protobuf_Payload_PropertyValue_PropertyValueExtension, extensions, extensions, 0),
    PB_LAST_FIELD
};

const pb_field_t com_cirruslink_sparkplug_protobuf_Payload_PropertySet_fields[4] = {
    PB_FIELD(  1, STRING  , REPEATED, CALLBACK, FIRST, com_cirruslink_sparkplug_protobuf_Payload_PropertySet, keys, keys, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_PropertySet, values, keys, &com_cirruslink_sparkplug_protobuf_Payload_PropertyValue_fields),
    PB_FIELD(  3, EXTENSION, OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_PropertySet, extensions, values, 0),
    PB_LAST_FIELD
};

const pb_field_t com_cirruslink_sparkplug_protobuf_Payload_PropertySetList_fields[3] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, com_cirruslink_sparkplug_protobuf_Payload_PropertySetList, propertyset, propertyset, &com_cirruslink_sparkplug_protobuf_Payload_PropertySet_fields),
    PB_FIELD(  2, EXTENSION, OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_PropertySetList, extensions, propertyset, 0),
    PB_LAST_FIELD
};

const pb_field_t com_cirruslink_sparkplug_protobuf_Payload_MetaData_fields[10] = {
    PB_FIELD(  1, BOOL    , OPTIONAL, STATIC  , FIRST, com_cirruslink_sparkplug_protobuf_Payload_MetaData, isMultiPart, isMultiPart, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_MetaData, content_type, isMultiPart, 0),
    PB_FIELD(  3, UINT64  , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_MetaData, size, content_type, 0),
    PB_FIELD(  4, UINT64  , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_MetaData, seq, size, 0),
    PB_FIELD(  5, STRING  , OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_MetaData, file_name, seq, 0),
    PB_FIELD(  6, STRING  , OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_MetaData, file_type, file_name, 0),
    PB_FIELD(  7, STRING  , OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_MetaData, md5, file_type, 0),
    PB_FIELD(  8, STRING  , OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_MetaData, description, md5, 0),
    PB_FIELD(  9, EXTENSION, OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_MetaData, extensions, description, 0),
    PB_LAST_FIELD
};

const pb_field_t com_cirruslink_sparkplug_protobuf_Payload_Metric_fields[19] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, FIRST, com_cirruslink_sparkplug_protobuf_Payload_Metric, name, name, 0),
    PB_FIELD(  2, UINT64  , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric, alias, name, 0),
    PB_FIELD(  3, UINT64  , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric, timestamp, alias, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric, datatype, timestamp, 0),
    PB_FIELD(  5, BOOL    , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric, historical, datatype, 0),
    PB_FIELD(  6, BOOL    , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric, transient, historical, 0),
    PB_FIELD(  7, BOOL    , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric, null, transient, 0),
    PB_FIELD(  8, MESSAGE , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric, metadata, null, &com_cirruslink_sparkplug_protobuf_Payload_MetaData_fields),
    PB_ONEOF_FIELD(value,   9, UINT32  , ONEOF, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric, int_value, metadata, 0),
    PB_ONEOF_FIELD(value,  10, UINT64  , ONEOF, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric, long_value, metadata, 0),
    PB_ONEOF_FIELD(value,  11, FLOAT   , ONEOF, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric, float_value, metadata, 0),
    PB_ONEOF_FIELD(value,  12, DOUBLE  , ONEOF, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric, double_value, metadata, 0),
    PB_ONEOF_FIELD(value,  13, BOOL    , ONEOF, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric, boolean_value, metadata, 0),
    PB_ONEOF_FIELD(value,  14, STRING  , ONEOF, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric, string_value, metadata, 0),
    PB_ONEOF_FIELD(value,  15, BYTES   , ONEOF, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric, bytes_value, metadata, 0),
    PB_ONEOF_FIELD(value,  16, MESSAGE , ONEOF, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric, dataset_value, metadata, &com_cirruslink_sparkplug_protobuf_Payload_DataSet_fields),
    PB_ONEOF_FIELD(value,  17, MESSAGE , ONEOF, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric, template_value, metadata, &com_cirruslink_sparkplug_protobuf_Payload_Template_fields),
    PB_ONEOF_FIELD(value,  18, MESSAGE , ONEOF, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric, extension_value, metadata, &com_cirruslink_sparkplug_protobuf_Payload_Metric_MetricValueExtension_fields),
    PB_LAST_FIELD
};

const pb_field_t com_cirruslink_sparkplug_protobuf_Payload_Metric_MetricValueExtension_fields[2] = {
    PB_FIELD(  1, EXTENSION, OPTIONAL, CALLBACK, FIRST, com_cirruslink_sparkplug_protobuf_Payload_Metric_MetricValueExtension, extensions, extensions, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
#error Field descriptor for com_cirruslink_sparkplug_protobuf_Payload_Metric.bytes_value is too large. Define PB_FIELD_32BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
