/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.5 at Mon Aug  8 16:49:26 2016. */

#ifndef PB_SPARKPLUG_B_PB_H_INCLUDED
#define PB_SPARKPLUG_B_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _com_cirruslink_sparkplug_protobuf_Payload_Metric_DataType {
    com_cirruslink_sparkplug_protobuf_Payload_Metric_DataType_Unknown = 0,
    com_cirruslink_sparkplug_protobuf_Payload_Metric_DataType_Int1 = 1,
    com_cirruslink_sparkplug_protobuf_Payload_Metric_DataType_Int2 = 2,
    com_cirruslink_sparkplug_protobuf_Payload_Metric_DataType_Int4 = 3,
    com_cirruslink_sparkplug_protobuf_Payload_Metric_DataType_Int8 = 4,
    com_cirruslink_sparkplug_protobuf_Payload_Metric_DataType_Float4 = 5,
    com_cirruslink_sparkplug_protobuf_Payload_Metric_DataType_Float8 = 6,
    com_cirruslink_sparkplug_protobuf_Payload_Metric_DataType_Boolean = 7,
    com_cirruslink_sparkplug_protobuf_Payload_Metric_DataType_String = 8,
    com_cirruslink_sparkplug_protobuf_Payload_Metric_DataType_DateTime = 9,
    com_cirruslink_sparkplug_protobuf_Payload_Metric_DataType_Dataset = 10,
    com_cirruslink_sparkplug_protobuf_Payload_Metric_DataType_Text = 11,
    com_cirruslink_sparkplug_protobuf_Payload_Metric_DataType_Bytes = 12,
    com_cirruslink_sparkplug_protobuf_Payload_Metric_DataType_File = 13,
    com_cirruslink_sparkplug_protobuf_Payload_Metric_DataType_UdtDef = 14,
    com_cirruslink_sparkplug_protobuf_Payload_Metric_DataType_UdtInst = 15
} com_cirruslink_sparkplug_protobuf_Payload_Metric_DataType;

typedef enum _com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value_DataType {
    com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value_DataType_Unknown = 0,
    com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value_DataType_Int1 = 1,
    com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value_DataType_Int2 = 2,
    com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value_DataType_Int4 = 3,
    com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value_DataType_Int8 = 4,
    com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value_DataType_Float4 = 5,
    com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value_DataType_Float8 = 6,
    com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value_DataType_Boolean = 7,
    com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value_DataType_String = 8,
    com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value_DataType_DateTime = 9,
    com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value_DataType_Text = 10,
    com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value_DataType_Null = 11
} com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value_DataType;

/* Struct definitions */
typedef struct _com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Row {
    pb_callback_t element;
    pb_extension_t *extensions;
/* @@protoc_insertion_point(struct:com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Row) */
} com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Row;

typedef struct _com_cirruslink_sparkplug_protobuf_Payload {
    bool has_timestamp;
    uint64_t timestamp;
    pb_callback_t metric;
    bool has_seq;
    uint64_t seq;
    pb_callback_t uuid;
    pb_callback_t body;
    pb_extension_t *extensions;
/* @@protoc_insertion_point(struct:com_cirruslink_sparkplug_protobuf_Payload) */
} com_cirruslink_sparkplug_protobuf_Payload;

typedef struct _com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet {
    bool has_num_of_columns;
    uint64_t num_of_columns;
    pb_callback_t columns;
    pb_callback_t rows;
    pb_extension_t *extensions;
/* @@protoc_insertion_point(struct:com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet) */
} com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet;

typedef struct _com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value {
    bool has_type;
    com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value_DataType type;
    bool has_int_value;
    uint32_t int_value;
    bool has_long_value;
    uint64_t long_value;
    bool has_float_value;
    float float_value;
    bool has_double_value;
    double double_value;
    bool has_boolean_value;
    bool boolean_value;
    pb_callback_t string_value;
    pb_extension_t *extensions;
/* @@protoc_insertion_point(struct:com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value) */
} com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value;

typedef struct _com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData {
    bool has_isMultiPart;
    bool isMultiPart;
    bool has_isScript;
    bool isScript;
    pb_callback_t units;
    pb_callback_t content_type;
    bool has_size;
    uint64_t size;
    pb_callback_t algorithm;
    pb_callback_t format;
    bool has_seq;
    uint64_t seq;
    pb_callback_t file_name;
    pb_callback_t file_type;
    pb_callback_t md5;
    bool has_remove;
    bool remove;
    pb_callback_t typeId;
    pb_callback_t description;
    pb_extension_t *extensions;
/* @@protoc_insertion_point(struct:com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData) */
} com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData;

typedef struct _com_cirruslink_sparkplug_protobuf_Payload_Metric {
    pb_callback_t name;
    bool has_alias;
    uint64_t alias;
    bool has_timestamp;
    uint64_t timestamp;
    bool has_datatype;
    com_cirruslink_sparkplug_protobuf_Payload_Metric_DataType datatype;
    bool has_historical;
    bool historical;
    bool has_metadata;
    com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData metadata;
    bool has_int_value;
    uint32_t int_value;
    bool has_long_value;
    uint64_t long_value;
    bool has_float_value;
    float float_value;
    bool has_double_value;
    double double_value;
    bool has_boolean_value;
    bool boolean_value;
    pb_callback_t string_value;
    pb_callback_t bytes_value;
    bool has_dataset_value;
    com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet dataset_value;
    pb_callback_t members;
    pb_extension_t *extensions;
/* @@protoc_insertion_point(struct:com_cirruslink_sparkplug_protobuf_Payload_Metric) */
} com_cirruslink_sparkplug_protobuf_Payload_Metric;

/* Default values for struct fields */

/* Initializer values for message structs */
#define com_cirruslink_sparkplug_protobuf_Payload_init_default {false, 0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, NULL}
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_init_default {{{NULL}, NULL}, false, 0, false, 0, false, (com_cirruslink_sparkplug_protobuf_Payload_Metric_DataType)0, false, 0, false, com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData_init_default, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_init_default, {{NULL}, NULL}, NULL}
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData_init_default {false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, NULL}
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_init_default {false, 0, {{NULL}, NULL}, {{NULL}, NULL}, NULL}
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value_init_default {false, (com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value_DataType)0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, NULL}
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Row_init_default {{{NULL}, NULL}, NULL}
#define com_cirruslink_sparkplug_protobuf_Payload_init_zero {false, 0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, NULL}
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_init_zero {{{NULL}, NULL}, false, 0, false, 0, false, (com_cirruslink_sparkplug_protobuf_Payload_Metric_DataType)0, false, 0, false, com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData_init_zero, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_init_zero, {{NULL}, NULL}, NULL}
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData_init_zero {false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, NULL}
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_init_zero {false, 0, {{NULL}, NULL}, {{NULL}, NULL}, NULL}
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value_init_zero {false, (com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value_DataType)0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, NULL}
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Row_init_zero {{{NULL}, NULL}, NULL}

/* Field tags (for use in manual encoding/decoding) */
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Row_element_tag 1
#define com_cirruslink_sparkplug_protobuf_Payload_timestamp_tag 1
#define com_cirruslink_sparkplug_protobuf_Payload_metric_tag 2
#define com_cirruslink_sparkplug_protobuf_Payload_seq_tag 3
#define com_cirruslink_sparkplug_protobuf_Payload_uuid_tag 4
#define com_cirruslink_sparkplug_protobuf_Payload_body_tag 5
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_num_of_columns_tag 1
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_columns_tag 2
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_rows_tag 3
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value_type_tag 1
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value_int_value_tag 2
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value_long_value_tag 3
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value_float_value_tag 4
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value_double_value_tag 5
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value_boolean_value_tag 6
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value_string_value_tag 7
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData_isMultiPart_tag 1
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData_isScript_tag 2
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData_units_tag 3
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData_content_type_tag 4
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData_size_tag 5
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData_algorithm_tag 6
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData_format_tag 7
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData_seq_tag 8
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData_file_name_tag 9
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData_file_type_tag 10
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData_md5_tag 11
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData_remove_tag 12
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData_typeId_tag 13
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData_description_tag 14
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_name_tag 1
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_alias_tag 2
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_timestamp_tag 3
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_datatype_tag 4
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_historical_tag 5
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_metadata_tag 6
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_int_value_tag 7
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_long_value_tag 8
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_float_value_tag 9
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_double_value_tag 10
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_boolean_value_tag 11
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_string_value_tag 12
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_bytes_value_tag 13
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_dataset_value_tag 14
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_members_tag 15

/* Struct field encoding specification for nanopb */
extern const pb_field_t com_cirruslink_sparkplug_protobuf_Payload_fields[7];
extern const pb_field_t com_cirruslink_sparkplug_protobuf_Payload_Metric_fields[17];
extern const pb_field_t com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData_fields[16];
extern const pb_field_t com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_fields[5];
extern const pb_field_t com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value_fields[9];
extern const pb_field_t com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Row_fields[3];

/* Maximum encoded size of messages (where known) */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SPARKPLUG_B_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
