/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.5 at Mon Aug  8 16:49:26 2016. */

#include "sparkplug_b.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t com_cirruslink_sparkplug_protobuf_Payload_fields[7] = {
    PB_FIELD(  1, UINT64  , OPTIONAL, STATIC  , FIRST, com_cirruslink_sparkplug_protobuf_Payload, timestamp, timestamp, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload, metric, timestamp, &com_cirruslink_sparkplug_protobuf_Payload_Metric_fields),
    PB_FIELD(  3, UINT64  , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload, seq, metric, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload, uuid, seq, 0),
    PB_FIELD(  5, BYTES   , OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload, body, uuid, 0),
    PB_FIELD(  6, EXTENSION, OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload, extensions, body, 0),
    PB_LAST_FIELD
};

const pb_field_t com_cirruslink_sparkplug_protobuf_Payload_Metric_fields[17] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, FIRST, com_cirruslink_sparkplug_protobuf_Payload_Metric, name, name, 0),
    PB_FIELD(  2, UINT64  , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric, alias, name, 0),
    PB_FIELD(  3, UINT64  , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric, timestamp, alias, 0),
    PB_FIELD(  4, UENUM   , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric, datatype, timestamp, 0),
    PB_FIELD(  5, BOOL    , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric, historical, datatype, 0),
    PB_FIELD(  6, MESSAGE , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric, metadata, historical, &com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData_fields),
    PB_FIELD(  7, UINT32  , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric, int_value, metadata, 0),
    PB_FIELD(  8, UINT64  , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric, long_value, int_value, 0),
    PB_FIELD(  9, FLOAT   , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric, float_value, long_value, 0),
    PB_FIELD( 10, DOUBLE  , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric, double_value, float_value, 0),
    PB_FIELD( 11, BOOL    , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric, boolean_value, double_value, 0),
    PB_FIELD( 12, STRING  , OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric, string_value, boolean_value, 0),
    PB_FIELD( 13, BYTES   , OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric, bytes_value, string_value, 0),
    PB_FIELD( 14, MESSAGE , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric, dataset_value, bytes_value, &com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_fields),
    PB_FIELD( 15, MESSAGE , REPEATED, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric, members, dataset_value, &com_cirruslink_sparkplug_protobuf_Payload_Metric_fields),
    PB_FIELD( 16, EXTENSION, OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric, extensions, members, 0),
    PB_LAST_FIELD
};

const pb_field_t com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData_fields[16] = {
    PB_FIELD(  1, BOOL    , OPTIONAL, STATIC  , FIRST, com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData, isMultiPart, isMultiPart, 0),
    PB_FIELD(  2, BOOL    , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData, isScript, isMultiPart, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData, units, isScript, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData, content_type, units, 0),
    PB_FIELD(  5, UINT64  , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData, size, content_type, 0),
    PB_FIELD(  6, STRING  , OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData, algorithm, size, 0),
    PB_FIELD(  7, STRING  , OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData, format, algorithm, 0),
    PB_FIELD(  8, UINT64  , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData, seq, format, 0),
    PB_FIELD(  9, STRING  , OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData, file_name, seq, 0),
    PB_FIELD( 10, STRING  , OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData, file_type, file_name, 0),
    PB_FIELD( 11, STRING  , OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData, md5, file_type, 0),
    PB_FIELD( 12, BOOL    , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData, remove, md5, 0),
    PB_FIELD( 13, STRING  , OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData, typeId, remove, 0),
    PB_FIELD( 14, STRING  , OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData, description, typeId, 0),
    PB_FIELD( 15, EXTENSION, OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData, extensions, description, 0),
    PB_LAST_FIELD
};

const pb_field_t com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_fields[5] = {
    PB_FIELD(  1, UINT64  , OPTIONAL, STATIC  , FIRST, com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet, num_of_columns, num_of_columns, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet, columns, num_of_columns, &com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value_fields),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet, rows, columns, &com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Row_fields),
    PB_FIELD(  4, EXTENSION, OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet, extensions, rows, 0),
    PB_LAST_FIELD
};

const pb_field_t com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value_fields[9] = {
    PB_FIELD(  1, UENUM   , OPTIONAL, STATIC  , FIRST, com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value, type, type, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value, int_value, type, 0),
    PB_FIELD(  3, UINT64  , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value, long_value, int_value, 0),
    PB_FIELD(  4, FLOAT   , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value, float_value, long_value, 0),
    PB_FIELD(  5, DOUBLE  , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value, double_value, float_value, 0),
    PB_FIELD(  6, BOOL    , OPTIONAL, STATIC  , OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value, boolean_value, double_value, 0),
    PB_FIELD(  7, STRING  , OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value, string_value, boolean_value, 0),
    PB_FIELD(  8, EXTENSION, OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value, extensions, string_value, 0),
    PB_LAST_FIELD
};

const pb_field_t com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Row_fields[3] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Row, element, element, &com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value_fields),
    PB_FIELD(  2, EXTENSION, OPTIONAL, CALLBACK, OTHER, com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Row, extensions, element, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(com_cirruslink_sparkplug_protobuf_Payload, metric) < 65536 && pb_membersize(com_cirruslink_sparkplug_protobuf_Payload_Metric, metadata) < 65536 && pb_membersize(com_cirruslink_sparkplug_protobuf_Payload_Metric, dataset_value) < 65536 && pb_membersize(com_cirruslink_sparkplug_protobuf_Payload_Metric, members) < 65536 && pb_membersize(com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet, columns) < 65536 && pb_membersize(com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet, rows) < 65536 && pb_membersize(com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Row, element) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_com_cirruslink_sparkplug_protobuf_Payload_com_cirruslink_sparkplug_protobuf_Payload_Metric_com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData_com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value_com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Row)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(com_cirruslink_sparkplug_protobuf_Payload, metric) < 256 && pb_membersize(com_cirruslink_sparkplug_protobuf_Payload_Metric, metadata) < 256 && pb_membersize(com_cirruslink_sparkplug_protobuf_Payload_Metric, dataset_value) < 256 && pb_membersize(com_cirruslink_sparkplug_protobuf_Payload_Metric, members) < 256 && pb_membersize(com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet, columns) < 256 && pb_membersize(com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet, rows) < 256 && pb_membersize(com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Row, element) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_com_cirruslink_sparkplug_protobuf_Payload_com_cirruslink_sparkplug_protobuf_Payload_Metric_com_cirruslink_sparkplug_protobuf_Payload_Metric_MetaData_com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Value_com_cirruslink_sparkplug_protobuf_Payload_Metric_DataSet_Row)
#endif


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
